package gui;

import javax.swing.JOptionPane;
import sorters.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David Buzatto
 */
public class FramePrincipal extends javax.swing.JFrame {

    public FramePrincipal() {
        initComponents();
        setExtendedState( MAXIMIZED_BOTH );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        scroll = new javax.swing.JScrollPane();
        panel = new SorterPanel();
        panelConf = new javax.swing.JPanel();
        labelAlgo = new javax.swing.JLabel();
        rbBubble = new javax.swing.JRadioButton();
        rbShell = new javax.swing.JRadioButton();
        rbInsertion = new javax.swing.JRadioButton();
        rbSelection = new javax.swing.JRadioButton();
        rbHeap = new javax.swing.JRadioButton();
        rbQuick = new javax.swing.JRadioButton();
        labelAmount = new javax.swing.JLabel();
        fieldAmount = new javax.swing.JTextField();
        checkShowNums = new javax.swing.JCheckBox();
        btnSort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sortings - David Buzatto");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        scroll.setViewportView(panel);

        panelConf.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        labelAlgo.setText("Sorting Algorithm:");

        grupo.add(rbBubble);
        rbBubble.setSelected(true);
        rbBubble.setText("Bubble");

        grupo.add(rbShell);
        rbShell.setText("Shell");

        grupo.add(rbInsertion);
        rbInsertion.setText("Insersion");

        grupo.add(rbSelection);
        rbSelection.setText("Selection");

        grupo.add(rbHeap);
        rbHeap.setText("Heap");

        grupo.add(rbQuick);
        rbQuick.setText("Quick");

        labelAmount.setText("Number amount:");

        fieldAmount.setText("10");

        checkShowNums.setText("Show numbers");

        btnSort.setText("Sort it!");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConfLayout = new javax.swing.GroupLayout(panelConf);
        panelConf.setLayout(panelConfLayout);
        panelConfLayout.setHorizontalGroup(
            panelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAlgo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelAmount, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConfLayout.createSequentialGroup()
                        .addComponent(rbBubble)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbShell)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbInsertion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbSelection)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbHeap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbQuick))
                    .addGroup(panelConfLayout.createSequentialGroup()
                        .addComponent(fieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkShowNums)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                        .addComponent(btnSort))))
        );
        panelConfLayout.setVerticalGroup(
            panelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfLayout.createSequentialGroup()
                .addGroup(panelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlgo)
                    .addComponent(rbBubble)
                    .addComponent(rbShell)
                    .addComponent(rbInsertion)
                    .addComponent(rbSelection)
                    .addComponent(rbHeap)
                    .addComponent(rbQuick))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAmount)
                    .addComponent(fieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSort)
                    .addComponent(checkShowNums))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelConf, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-669)/2, (screenSize.height-455)/2, 669, 455);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed

        try {

            int quant = Integer.parseInt( fieldAmount.getText() );
            Sorter sorter = null;

            if ( rbBubble.isSelected() ) {
                sorter = new BubbleSorter();
            } else if ( rbShell.isSelected() ) {
                sorter = new ShellSorter();
            } else if ( rbInsertion.isSelected() ) {
                sorter = new InsertionSorter();
            } else if ( rbSelection.isSelected() ) {
                sorter = new SelectionSorter();
            } else if ( rbHeap.isSelected() ) {
                sorter = new HeapSorter();
            } else if ( rbQuick.isSelected() ) {
                sorter = new QuickSorter();
            }

            Integer[] array = generateRandomArray( quant );
            sorter.sortIt( array );

            ((SorterPanel)panel).setSorter( sorter );
            ((SorterPanel)panel).setShowLabels( checkShowNums.isSelected() );
            panel.repaint();

        } catch ( NumberFormatException exc ) {
            JOptionPane.showMessageDialog( null, "You need to input a number in the field number amount!",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSortActionPerformed

    private Integer[] generateRandomArray( int amount ) {
        Integer[] array = new Integer[ amount ];

        for ( int i = 0; i < array.length; i++ ) {
            array[i] = ( int ) ( Math.random() * 100 );
        }

        return array;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSort;
    private javax.swing.JCheckBox checkShowNums;
    private javax.swing.JTextField fieldAmount;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel labelAlgo;
    private javax.swing.JLabel labelAmount;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelConf;
    private javax.swing.JRadioButton rbBubble;
    private javax.swing.JRadioButton rbHeap;
    private javax.swing.JRadioButton rbInsertion;
    private javax.swing.JRadioButton rbQuick;
    private javax.swing.JRadioButton rbSelection;
    private javax.swing.JRadioButton rbShell;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables

}
