/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package algoritmosbuscaordenacaografico.gui;

import algoritmosbuscaordenacaografico.engine.DrawEngine;
import algoritmosbuscaordenacaografico.sorters.*;
import java.awt.Color;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 *
 * @author David Buzatto
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    
    public JanelaPrincipal() {
        
        initComponents();
        //setExtendedState( MAXIMIZED_BOTH );
        
        ( ( DrawPanel ) painelBubbleV1 ).setCorNormal( new Color( 98, 218, 154 ) );
        ( ( DrawPanel ) painelBubbleV1 ).setCorAtivo( Color.RED );
        ( ( DrawPanel ) painelBubbleV1 ).setCorPivoOuEleito( Color.BLUE );
        
        ( ( DrawPanel ) painelBubbleV2 ).setCorNormal( new Color( 54, 218, 130 ) );
        ( ( DrawPanel ) painelBubbleV2 ).setCorAtivo( Color.RED );
        ( ( DrawPanel ) painelBubbleV2 ).setCorPivoOuEleito( Color.BLUE );
        
        ( ( DrawPanel ) painelBubbleV3 ).setCorNormal( new Color( 0, 180, 84 ) );
        ( ( DrawPanel ) painelBubbleV3 ).setCorAtivo( Color.RED );
        ( ( DrawPanel ) painelBubbleV3 ).setCorPivoOuEleito( Color.BLUE );
        
        ( ( DrawPanel ) painelBubbleV4 ).setCorNormal( new Color( 34, 135, 81 ) );
        ( ( DrawPanel ) painelBubbleV4 ).setCorAtivo( Color.RED );
        ( ( DrawPanel ) painelBubbleV4 ).setCorPivoOuEleito( Color.BLUE );
        
        ( ( DrawPanel ) painelSelection ).setCorNormal( new Color( 96, 50, 190 ) );
        ( ( DrawPanel ) painelSelection ).setCorAtivo( new Color( 255, 131, 0 ) );
        ( ( DrawPanel ) painelSelection ).setCorPivoOuEleito( Color.YELLOW );
        
        ( ( DrawPanel ) painelInsertion ).setCorNormal( new Color( 18, 64, 171 ) );
        ( ( DrawPanel ) painelInsertion ).setCorAtivo( new Color( 255, 131, 0 ) );
        ( ( DrawPanel ) painelInsertion ).setCorPivoOuEleito( Color.YELLOW );
        
        ( ( DrawPanel ) painelMerge ).setCorNormal( new Color( 239,12,24 ) );
        ( ( DrawPanel ) painelMerge ).setCorAtivo( Color.GREEN );
        ( ( DrawPanel ) painelMerge ).setCorPivoOuEleito( Color.BLUE );
        
        ( ( DrawPanel ) painelQuick ).setCorNormal( new Color( 243,110,13 ) );
        ( ( DrawPanel ) painelQuick ).setCorAtivo( Color.GREEN );
        ( ( DrawPanel ) painelQuick ).setCorPivoOuEleito( Color.BLUE );
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBubbleV1 = new DrawPanel();
        lblBubbleV1 = new javax.swing.JLabel();
        painelBubbleV2 = new DrawPanel();
        lblBubbleV2 = new javax.swing.JLabel();
        painelBubbleV3 = new DrawPanel();
        lblBubbleV3 = new javax.swing.JLabel();
        painelBubbleV4 = new DrawPanel();
        lblBubbleV4 = new javax.swing.JLabel();
        painelSelection = new DrawPanel();
        lblSelection = new javax.swing.JLabel();
        painelInsertion = new DrawPanel();
        lblInsertion = new javax.swing.JLabel();
        painelMerge = new DrawPanel();
        lblMerge = new javax.swing.JLabel();
        painelQuick = new DrawPanel();
        lblQuick = new javax.swing.JLabel();
        painelConfiguracoes = new javax.swing.JPanel();
        lblTempo = new javax.swing.JLabel();
        fieldTempo = new javax.swing.JTextField();
        btnOrdenar = new javax.swing.JButton();
        painelMostrar = new javax.swing.JPanel();
        checkBubbleV1 = new javax.swing.JCheckBox();
        checkBubbleV2 = new javax.swing.JCheckBox();
        checkBubbleV3 = new javax.swing.JCheckBox();
        checkBubbleV4 = new javax.swing.JCheckBox();
        checkSelection = new javax.swing.JCheckBox();
        checkInsertion = new javax.swing.JCheckBox();
        checkMerge = new javax.swing.JCheckBox();
        checkQuick = new javax.swing.JCheckBox();
        btnNenhum = new javax.swing.JButton();
        btnTodos = new javax.swing.JButton();
        checkPiorCaso = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algoritmos de Ordenação (Simulação de Execução) - David Buzatto");

        painelBubbleV1.setBackground(new java.awt.Color(255, 255, 255));
        painelBubbleV1.setPreferredSize(new java.awt.Dimension(270, 200));

        lblBubbleV1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblBubbleV1.setForeground(new java.awt.Color(98, 218, 154));
        lblBubbleV1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBubbleV1.setText("Bubble Sort V1");

        javax.swing.GroupLayout painelBubbleV1Layout = new javax.swing.GroupLayout(painelBubbleV1);
        painelBubbleV1.setLayout(painelBubbleV1Layout);
        painelBubbleV1Layout.setHorizontalGroup(
            painelBubbleV1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBubbleV1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBubbleV1)
                .addGap(185, 185, 185))
        );
        painelBubbleV1Layout.setVerticalGroup(
            painelBubbleV1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBubbleV1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBubbleV1)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        painelBubbleV2.setBackground(new java.awt.Color(255, 255, 255));
        painelBubbleV2.setPreferredSize(new java.awt.Dimension(270, 200));

        lblBubbleV2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblBubbleV2.setForeground(new java.awt.Color(54, 218, 130));
        lblBubbleV2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBubbleV2.setText("Bubble Sort V2");

        javax.swing.GroupLayout painelBubbleV2Layout = new javax.swing.GroupLayout(painelBubbleV2);
        painelBubbleV2.setLayout(painelBubbleV2Layout);
        painelBubbleV2Layout.setHorizontalGroup(
            painelBubbleV2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBubbleV2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBubbleV2)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        painelBubbleV2Layout.setVerticalGroup(
            painelBubbleV2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBubbleV2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBubbleV2)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        painelBubbleV3.setBackground(new java.awt.Color(255, 255, 255));
        painelBubbleV3.setPreferredSize(new java.awt.Dimension(270, 200));

        lblBubbleV3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblBubbleV3.setForeground(new java.awt.Color(0, 180, 84));
        lblBubbleV3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBubbleV3.setText("Bubble Sort V3");

        javax.swing.GroupLayout painelBubbleV3Layout = new javax.swing.GroupLayout(painelBubbleV3);
        painelBubbleV3.setLayout(painelBubbleV3Layout);
        painelBubbleV3Layout.setHorizontalGroup(
            painelBubbleV3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBubbleV3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBubbleV3)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        painelBubbleV3Layout.setVerticalGroup(
            painelBubbleV3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBubbleV3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBubbleV3)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        painelBubbleV4.setBackground(new java.awt.Color(255, 255, 255));
        painelBubbleV4.setPreferredSize(new java.awt.Dimension(270, 200));

        lblBubbleV4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblBubbleV4.setForeground(new java.awt.Color(34, 135, 81));
        lblBubbleV4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBubbleV4.setText("Bubble Sort V4");

        javax.swing.GroupLayout painelBubbleV4Layout = new javax.swing.GroupLayout(painelBubbleV4);
        painelBubbleV4.setLayout(painelBubbleV4Layout);
        painelBubbleV4Layout.setHorizontalGroup(
            painelBubbleV4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBubbleV4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBubbleV4)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        painelBubbleV4Layout.setVerticalGroup(
            painelBubbleV4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBubbleV4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBubbleV4)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        painelSelection.setBackground(new java.awt.Color(255, 255, 255));
        painelSelection.setPreferredSize(new java.awt.Dimension(270, 200));

        lblSelection.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSelection.setForeground(new java.awt.Color(131, 13, 160));
        lblSelection.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSelection.setText("Selection Sort");

        javax.swing.GroupLayout painelSelectionLayout = new javax.swing.GroupLayout(painelSelection);
        painelSelection.setLayout(painelSelectionLayout);
        painelSelectionLayout.setHorizontalGroup(
            painelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSelectionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSelection)
                .addGap(191, 191, 191))
        );
        painelSelectionLayout.setVerticalGroup(
            painelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelection)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        painelInsertion.setBackground(new java.awt.Color(255, 255, 255));
        painelInsertion.setPreferredSize(new java.awt.Dimension(270, 200));

        lblInsertion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblInsertion.setForeground(new java.awt.Color(18, 64, 171));
        lblInsertion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInsertion.setText("Insertion Sort");

        javax.swing.GroupLayout painelInsertionLayout = new javax.swing.GroupLayout(painelInsertion);
        painelInsertion.setLayout(painelInsertionLayout);
        painelInsertionLayout.setHorizontalGroup(
            painelInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInsertionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInsertion)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        painelInsertionLayout.setVerticalGroup(
            painelInsertionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInsertionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInsertion)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        painelMerge.setBackground(new java.awt.Color(255, 255, 255));
        painelMerge.setPreferredSize(new java.awt.Dimension(270, 200));

        lblMerge.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblMerge.setForeground(new java.awt.Color(239, 12, 24));
        lblMerge.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMerge.setText("Merge Sort");

        javax.swing.GroupLayout painelMergeLayout = new javax.swing.GroupLayout(painelMerge);
        painelMerge.setLayout(painelMergeLayout);
        painelMergeLayout.setHorizontalGroup(
            painelMergeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMergeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMerge)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        painelMergeLayout.setVerticalGroup(
            painelMergeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMergeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMerge)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        painelQuick.setBackground(new java.awt.Color(255, 255, 255));
        painelQuick.setPreferredSize(new java.awt.Dimension(270, 200));

        lblQuick.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblQuick.setForeground(new java.awt.Color(243, 110, 13));
        lblQuick.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQuick.setText("Quick Sort");

        javax.swing.GroupLayout painelQuickLayout = new javax.swing.GroupLayout(painelQuick);
        painelQuick.setLayout(painelQuickLayout);
        painelQuickLayout.setHorizontalGroup(
            painelQuickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelQuickLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuick)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        painelQuickLayout.setVerticalGroup(
            painelQuickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelQuickLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuick)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        lblTempo.setText("Tempo entre iterações (ms):");

        fieldTempo.setText("300");

        btnOrdenar.setText("Iniciar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        painelMostrar.setBorder(javax.swing.BorderFactory.createTitledBorder("Mostrar"));

        checkBubbleV1.setSelected(true);
        checkBubbleV1.setText("Bubble Sort V1");

        checkBubbleV2.setSelected(true);
        checkBubbleV2.setText("Bubble Sort V2");

        checkBubbleV3.setSelected(true);
        checkBubbleV3.setText("Bubble Sort V3");

        checkBubbleV4.setSelected(true);
        checkBubbleV4.setText("Bubble Sort V4");

        checkSelection.setSelected(true);
        checkSelection.setText("Selection Sort");

        checkInsertion.setSelected(true);
        checkInsertion.setText("Insertion Sort");

        checkMerge.setSelected(true);
        checkMerge.setText("Merge Sort");

        checkQuick.setSelected(true);
        checkQuick.setText("Quick Sort");

        javax.swing.GroupLayout painelMostrarLayout = new javax.swing.GroupLayout(painelMostrar);
        painelMostrar.setLayout(painelMostrarLayout);
        painelMostrarLayout.setHorizontalGroup(
            painelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMostrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBubbleV1)
                    .addComponent(checkSelection))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBubbleV2)
                    .addComponent(checkInsertion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBubbleV3)
                    .addComponent(checkMerge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkQuick)
                    .addComponent(checkBubbleV4))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        painelMostrarLayout.setVerticalGroup(
            painelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMostrarLayout.createSequentialGroup()
                .addGroup(painelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBubbleV1)
                    .addComponent(checkBubbleV2)
                    .addComponent(checkBubbleV3)
                    .addComponent(checkBubbleV4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkSelection)
                    .addComponent(checkInsertion)
                    .addComponent(checkMerge)
                    .addComponent(checkQuick)))
        );

        btnNenhum.setText("Nenhum");
        btnNenhum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNenhumActionPerformed(evt);
            }
        });

        btnTodos.setText("Todos");
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });

        checkPiorCaso.setText("Pior caso!");

        javax.swing.GroupLayout painelConfiguracoesLayout = new javax.swing.GroupLayout(painelConfiguracoes);
        painelConfiguracoes.setLayout(painelConfiguracoesLayout);
        painelConfiguracoesLayout.setHorizontalGroup(
            painelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfiguracoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelConfiguracoesLayout.createSequentialGroup()
                        .addComponent(btnTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNenhum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOrdenar))
                    .addGroup(painelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(painelMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(painelConfiguracoesLayout.createSequentialGroup()
                            .addComponent(lblTempo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fieldTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(checkPiorCaso))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelConfiguracoesLayout.setVerticalGroup(
            painelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConfiguracoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTempo)
                    .addComponent(fieldTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkPiorCaso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConfiguracoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrdenar)
                    .addComponent(btnNenhum)
                    .addComponent(btnTodos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(564, 564, 564)
                        .addComponent(painelConfiguracoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(painelBubbleV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(painelBubbleV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(painelBubbleV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(painelSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(painelInsertion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(painelMerge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelBubbleV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painelQuick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelBubbleV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelBubbleV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelBubbleV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelBubbleV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelInsertion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelMerge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelQuick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelConfiguracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1156)/2, (screenSize.height-638)/2, 1156, 638);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed

        btnOrdenar.setEnabled( false );
        btnNenhum.setEnabled( false );
        btnTodos.setEnabled( false );
        fieldTempo.setEnabled( false );
        checkPiorCaso.setEnabled( false );
        
        checkBubbleV1.setEnabled( false );
        checkBubbleV2.setEnabled( false );
        checkBubbleV3.setEnabled( false );
        checkBubbleV4.setEnabled( false );
        checkSelection.setEnabled( false );
        checkInsertion.setEnabled( false );
        checkMerge.setEnabled( false );
        checkQuick.setEnabled( false );
        
        int tempo = 300;
        int[] array = gerarArrayAleatorio( 39 );
        
        try {
            tempo = Integer.parseInt( fieldTempo.getText() );
        } catch ( NumberFormatException exc ) {}

        BubbleSorterV1 bubbleSorterV1 = new BubbleSorterV1();
        bubbleSorterV1.sortIt( array.clone() );

        BubbleSorterV2 bubbleSorterV2 = new BubbleSorterV2();
        bubbleSorterV2.sortIt( array.clone() );

        BubbleSorterV3 bubbleSorterV3 = new BubbleSorterV3();
        bubbleSorterV3.sortIt( array.clone() );

        BubbleSorterV4 bubbleSorterV4 = new BubbleSorterV4();
        bubbleSorterV4.sortIt( array.clone() );

        SelectionSorter selectionSorter = new SelectionSorter();
        selectionSorter.sortIt( array.clone() );

        InsertionSorter insertionSorter = new InsertionSorter();
        insertionSorter.sortIt( array.clone() );

        MergeSorter mergeSorter = new MergeSorter();
        mergeSorter.sortIt( array.clone() );

        QuickSorter quickSorter = new QuickSorter();
        quickSorter.sortIt( array.clone() );

        
        DrawEngine dBubbleEngineV1 = new DrawEngine( 
                bubbleSorterV1.getLista(), 
                ( DrawPanel ) painelBubbleV1, tempo );

        DrawEngine dBubbleEngineV2 = new DrawEngine( 
                bubbleSorterV2.getLista(), 
                ( DrawPanel ) painelBubbleV2, tempo );
                 
        DrawEngine dBubbleEngineV3 = new DrawEngine( 
                bubbleSorterV3.getLista(), 
                ( DrawPanel ) painelBubbleV3, tempo );

        DrawEngine dBubbleEngineV4 = new DrawEngine( 
                bubbleSorterV4.getLista(), 
                ( DrawPanel ) painelBubbleV4, tempo );

        DrawEngine dSelectionEngine = new DrawEngine( 
                selectionSorter.getLista(), 
                ( DrawPanel ) painelSelection, tempo );

        DrawEngine dInsertionEngine = new DrawEngine( 
                insertionSorter.getLista(), 
                ( DrawPanel ) painelInsertion, tempo );
        
        DrawEngine dMergeEngine = new DrawEngine( 
                mergeSorter.getLista(), 
                ( DrawPanel ) painelMerge, tempo );

        DrawEngine dQuickEngine = new DrawEngine( 
                quickSorter.getLista(), 
                ( DrawPanel ) painelQuick, tempo );
        
        
        ExecutorService s = Executors.newFixedThreadPool( 10 );
        
        if ( checkBubbleV1.isSelected() ) {
            s.submit( new Thread( dBubbleEngineV1 ) );
        }
        
        if ( checkBubbleV2.isSelected() ) {
            s.submit( new Thread( dBubbleEngineV2 ) );
        }
        
        if ( checkBubbleV3.isSelected() ) {
            s.submit( new Thread( dBubbleEngineV3 ) );
        }
        
        if ( checkBubbleV4.isSelected() ) {
            s.submit( new Thread( dBubbleEngineV4 ) );
        }
        
        if ( checkSelection.isSelected() ) {
            s.submit( new Thread( dSelectionEngine ) );
        }
        
        if ( checkInsertion.isSelected() ) {
            s.submit( new Thread( dInsertionEngine ) );
        }
        
        if ( checkMerge.isSelected() ) {
            s.submit( new Thread( dMergeEngine ) );
        }
        
        if ( checkQuick.isSelected() ) {
            s.submit( new Thread( dQuickEngine ) );
        }

    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnTodosActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_btnTodosActionPerformed
        
        checkBubbleV1.setSelected( true );
        checkBubbleV2.setSelected( true );
        checkBubbleV3.setSelected( true );
        checkBubbleV4.setSelected( true );
        checkSelection.setSelected( true );
        checkInsertion.setSelected( true );
        checkMerge.setSelected( true );
        checkQuick.setSelected( true );
        
    }//GEN-LAST:event_btnTodosActionPerformed

    private void btnNenhumActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_btnNenhumActionPerformed
        
        checkBubbleV1.setSelected( false );
        checkBubbleV2.setSelected( false );
        checkBubbleV3.setSelected( false );
        checkBubbleV4.setSelected( false );
        checkSelection.setSelected( false );
        checkInsertion.setSelected( false );
        checkMerge.setSelected( false );
        checkQuick.setSelected( false );
        
    }//GEN-LAST:event_btnNenhumActionPerformed

    private int[] gerarArrayAleatorio( int quantidade ) {
        
        int[] array = new int[ quantidade ];
        int temp;
        int pos;
        
        if ( checkPiorCaso.isSelected() ) {
            
            for ( int i = 0; i < array.length; i++ ) {
                array[i] = quantidade - i;
            }
            
        } else {
            
            for ( int i = 0; i < array.length; i++ ) {
                array[i] = i + 1;
            }

            for ( int i = 0; i < array.length; i++ ) {
                pos = ( int ) ( Math.random() * quantidade );
                temp = array[i];
                array[i] = array[pos];
                array[pos] = temp;
            }
            
        }

        return array;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNenhum;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnTodos;
    private javax.swing.JCheckBox checkBubbleV1;
    private javax.swing.JCheckBox checkBubbleV2;
    private javax.swing.JCheckBox checkBubbleV3;
    private javax.swing.JCheckBox checkBubbleV4;
    private javax.swing.JCheckBox checkInsertion;
    private javax.swing.JCheckBox checkMerge;
    private javax.swing.JCheckBox checkPiorCaso;
    private javax.swing.JCheckBox checkQuick;
    private javax.swing.JCheckBox checkSelection;
    private javax.swing.JTextField fieldTempo;
    private javax.swing.JLabel lblBubbleV1;
    private javax.swing.JLabel lblBubbleV2;
    private javax.swing.JLabel lblBubbleV3;
    private javax.swing.JLabel lblBubbleV4;
    private javax.swing.JLabel lblInsertion;
    private javax.swing.JLabel lblMerge;
    private javax.swing.JLabel lblQuick;
    private javax.swing.JLabel lblSelection;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JPanel painelBubbleV1;
    private javax.swing.JPanel painelBubbleV2;
    private javax.swing.JPanel painelBubbleV3;
    private javax.swing.JPanel painelBubbleV4;
    private javax.swing.JPanel painelConfiguracoes;
    private javax.swing.JPanel painelInsertion;
    private javax.swing.JPanel painelMerge;
    private javax.swing.JPanel painelMostrar;
    private javax.swing.JPanel painelQuick;
    private javax.swing.JPanel painelSelection;
    // End of variables declaration//GEN-END:variables

}
